/*
- MOV_ROLES
- MOV_MOVIES
- MOV_ACTORS
- MOV_MOVIES_GENRERS
- MOV_MOVIES_DIRECTORS
- MOV_DIRECTORS
- MOV_DIRECTORS_GENRERS
*/


desc JLEON.MOV_ROLES;

SELECT *
FROM JLEON.MOV_ROLES;

SELECT * 
FROM JLEON.MOV_MOVIES;

SELECT *
FROM JLEON.MOV_ACTORS;

SELECT *
FROM JLEON.MOV_MOVIES_GENRERS;

SELECT *
FROM JLEON.MOV_MOVIES_DIRECTORS;

SELECT *
FROM JLEON.MOV_DIRECTORS;

SELECT *
FROM JLEON.MOV_DIRECTORS_GENRERS;

--Punto6
SELECT * FROM ALL_CONSTRAINTS
where owner ='JLEON' and table_name in (
    'MOV_ROLES',
    'MOV_MOVIES',
    'MOV_ACTORS', 
    'MOV_MOVIES_GENRERS', 
    'MOV_MOVIES_DIRECTORS', 
    'MOV_DIRECTORS', 
    'MOV_DIRECTORS_GENRERS'
)
and constraint_type in ('R','P')
order by table_name;


select * from all_cons_columns
where constraint_name ='MOVIES_DIRECTORS_IBFK_2';
--Punto7
SELECT TO_CHAR(AVG(MM.RANK), 'fm990.00') "Promedio", MM.YEAR
FROM JLEON.MOV_MOVIES MM
GROUP BY MM.YEAR
ORDER BY MM.YEAR;

--Punto 8
SELECT DISTINCT
     MDD.FIRST_NAME, MDD.LAST_NAME, COUNT(MR.ACTOR_ID)
FROM 
    --(select distinct ACTOR_ID, MOVIE_ID from JLEON.MOV_ROLES ) MR ,
    JLEON.MOV_ROLES MR, 
    JLEON.MOV_MOVIES_DIRECTORS MD, 
    JLEON.MOV_DIRECTORS MDD
WHERE 
    MR.MOVIE_ID = MD.MOVIE_ID
    AND MD.DIRECTOR_ID=MDD.ID    
GROUP BY 
    MDD.FIRST_NAME, MDD.LAST_NAME
order by 1,2;

--Punto 9

SELECT M.GENRE , TO_CHAR(AVG(MM.RANK),'fm990.00') as "Promedio Genero"
FROM 
    JLEON.MOV_MOVIES_GENRERS M, 
    JLEON.MOV_MOVIES MM
WHERE 
    M.MOVIE_ID = MM.ID
GROUP BY 
    M.GENRE;

--Punto 10
/*
SELECT table1.*
FROM table1
LEFT JOIN table2 ON table1.column = table2.column
WHERE table2.column IS NULL;*/

SELECT distinct MDG.GENRE
FROM 
    JLEON.MOV_DIRECTORS_GENRERS MDG      
    LEFT JOIN     
    JLEON.MOV_MOVIES_GENRERS M
    ON 
         MDG.genre=m.genre
WHERE M.GENRE IS NULL;




